const produtosData = {
  brick: [
    {
      id: 'branco-rose',
      nome: 'Branco Rosé',
      categoria: 'Brick',
      sku: '56',
      preco: '139,90',
      descricao: 'Tons de branco com nuances rosadas — leveza e luminosidade.',
      descricaoLonga: 'Revestimento cerâmico artesanal com tons brancos e rosados, selecionado para ambientes sofisticados. Cada peça é batida à mão e retificada individualmente, garantindo precisão no acabamento.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Dormitório, Cozinha',
      imagens: ['brick-branco-rose-frontal.webp', 'brick-branco-rose-frontal-1.webp', 'brick-branco-rose-frontal-2.webp', 'brick-branco-rose-frontal-3.webp'],
      arquivo: 'produto-brick-branco-rose.html'
    },
    {
      id: 'eco-palha',
      nome: 'Eco Palha',
      categoria: 'Brick',
      sku: '57',
      preco: '139,90',
      descricao: 'Tom palha claro, com pontos minerais naturais.',
      descricaoLonga: 'Revestimento em tom palha claro com pontos minerais naturais visíveis. Cada peça é batida à mão e retificada individualmente.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Cozinha, Varanda',
      imagens: ['brick-eco-palha-frontal.webp', 'brick-eco-palha-frontal-1.webp', 'brick-eco-palha-frontal-2.webp', 'brick-eco-palha-frontal-3.webp'],
      arquivo: 'produto-brick-eco-palha.html'
    },
    {
      id: 'lumus',
      nome: 'Lumus',
      categoria: 'Brick',
      sku: '73',
      preco: '149,90',
      descricao: 'Mescla de tons terrosos com nuances acinzentadas.',
      descricaoLonga: 'Revestimento com mescla de tons terrosos e nuances acinzentadas. Ideal para projetos que buscam profundidade visual.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Escritório, Fachada',
      imagens: ['brick-lumus-frontal.webp', 'brick-lumus-frontal-1.webp', 'brick-lumus-frontal-2.webp', 'brick-lumus-frontal-3.webp'],
      arquivo: 'produto-brick-lumus.html'
    },
    {
      id: 'mescla-prime',
      nome: 'Mescla Prime',
      categoria: 'Brick',
      sku: '54',
      preco: '139,90',
      descricao: 'Mesclas escuras sobre base terrosa — profundidade em cada peça.',
      descricaoLonga: 'Revestimento com mesclas escuras sobre base terrosa que proporciona profundidade visual única em cada peça.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Dormitório, Fachada',
      imagens: ['brick-mescla-prime-frontal.webp', 'brick-mescla-prime-frontal-1.webp', 'brick-mescla-prime-frontal-2.webp', 'brick-mescla-prime-frontal-3.webp'],
      arquivo: 'produto-brick-mescla-prime.html'
    },
    {
      id: 'natura',
      nome: 'Natura',
      categoria: 'Brick',
      sku: '48',
      preco: '94,90',
      descricao: 'Terracota uniforme, extrudada e queimada a 950°C. Promoção especial.',
      descricaoLonga: 'Revestimento terracota uniforme, extrudado e queimado a 950°C. Oferece excelente custo-benefício com qualidade garantida.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Cozinha, Área gourmet',
      imagens: ['brick-natura-frontal.webp', 'brick-natura-frontal-1.webp', 'brick-natura-frontal-2.webp', 'brick-natura-frontal-3.webp'],
      arquivo: 'produto-brick-natura.html'
    },
    {
      id: 'rosso-prime',
      nome: 'Rosso Prime',
      categoria: 'Brick',
      sku: '53',
      preco: '129,90',
      descricao: 'Vermelho terracota uniforme — o mais vendido da linha.',
      descricaoLonga: 'Revestimento vermelho terracota uniforme, o mais vendido da linha da BRUTO. Versátil e ideal para diversos ambientes.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Cozinha, Fachada',
      imagens: ['brick-rosso-prime-frontal.webp', 'brick-rosso-prime-frontal-1.webp', 'brick-rosso-prime-frontal-2.webp', 'brick-rosso-prime-frontal-3.webp'],
      arquivo: 'produto-brick-rosso-prime.html'
    },
    {
      id: 'rusticatto-sertao',
      nome: 'Rusticatto do Sertão',
      categoria: 'Brick',
      sku: '61',
      preco: '149,90',
      descricao: 'Laranja claro, textura alta e acabamento artesanal exclusivo.',
      descricaoLonga: 'Revestimento laranja claro com textura alta e acabamento artesanal exclusivo. Perfeito para projetos de destaque.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Rústico',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Área gourmet, Fachada',
      imagens: ['brick-rusticatto-sertao-frontal.webp', 'brick-rusticatto-sertao-frontal-1.webp', 'brick-rusticatto-sertao-frontal-2.webp', 'brick-rusticatto-sertao-frontal-3.webp'],
      arquivo: 'produto-brick-rusticatto-sertao.html'
    },
    {
      id: 'rusticatto-fume',
      nome: 'Rusticatto Fumê',
      categoria: 'Brick',
      sku: '72',
      preco: '169,90',
      descricao: 'Extra rústico, tonalidade fumê escura e marcante.',
      descricaoLonga: 'Revestimento extra rústico com tonalidade fumê escura e muito marcante. Ideal para projetos contemporâneos.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Rústico',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Dormitório, Fachada',
      imagens: ['brick-rusticatto-fume-frontal.webp', 'brick-rusticatto-fume-frontal-1.webp', 'brick-rusticatto-fume-frontal-2.webp', 'brick-rusticatto-fume-frontal-3.webp'],
      arquivo: 'produto-brick-rusticatto-fume.html'
    },
    {
      id: 'rusticatto-rosso',
      nome: 'Rusticatto Rosso',
      categoria: 'Brick',
      sku: '77',
      preco: '144,90',
      descricao: 'Vermelho intenso, textura irregular e expressiva.',
      descricaoLonga: 'Revestimento vermelho intenso com textura irregular e muito expressiva. Perfeito para criar destaque.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Rústico',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Cozinha, Fachada',
      imagens: ['brick-rusticatto-rosso-frontal.webp', 'brick-rusticatto-rosso-frontal-1.webp', 'brick-rusticatto-rosso-frontal-2.webp', 'brick-rusticatto-rosso-frontal-3.webp'],
      arquivo: 'produto-brick-rusticatto-rosso.html'
    },
    {
      id: 'rusticatto-terra-negra',
      nome: 'Rusticatto Terra Negra',
      categoria: 'Brick',
      sku: '60',
      preco: '179,90',
      descricao: 'Tonalidade escura, inspirada nos tijolos de demolição europeus.',
      descricaoLonga: 'Revestimento com tonalidade escura inspirada nos tijolos de demolição europeus. Oferece elegância e sofisticação.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Rústico',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Dormitório, Fachada',
      imagens: ['brick-rusticatto-terra-negra-frontal.webp', 'brick-rusticatto-terra-negra-frontal-1.webp', 'brick-rusticatto-terra-negra-frontal-2.webp', 'brick-rusticatto-terra-negra-frontal-3.webp'],
      arquivo: 'produto-brick-rusticatto-terra-negra.html'
    },
    {
      id: 'terra-cerrado',
      nome: 'Terra do Cerrado',
      categoria: 'Brick',
      sku: '47',
      preco: '134,90',
      descricao: 'Mescla de laranja, vermelho e terroso — paginação única.',
      descricaoLonga: 'Revestimento com mescla de laranja, vermelho e terroso que oferece paginação única e acolhedora.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Área gourmet, Fachada',
      imagens: ['brick-terra-cerrado-frontal.webp', 'brick-terra-cerrado-frontal-1.webp', 'brick-terra-cerrado-frontal-2.webp', 'brick-terra-cerrado-frontal-3.webp'],
      arquivo: 'produto-brick-terra-cerrado.html'
    },
    {
      id: 'vulcano',
      nome: 'Vulcano',
      categoria: 'Brick',
      sku: '59',
      preco: '149,90',
      descricao: 'Mescla de tons terrosos com nuances acinzentadas.',
      descricaoLonga: 'Revestimento com mescla de tons terrosos e nuances acinzentadas. Versátil para projetos residenciais e comerciais.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Natural',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Escritório, Fachada',
      imagens: ['brick-vulcano-frontal.webp', 'brick-vulcano-frontal-1.webp', 'brick-vulcano-frontal-2.webp', 'brick-vulcano-frontal-3.webp'],
      arquivo: 'produto-brick-vulcano.html'
    }
  ],
  cimenticio: [
    {
      id: 'alpino',
      nome: 'Alpino',
      categoria: 'Cimentício',
      sku: 'Cimentício',
      preco: '169,90',
      descricao: 'Estética contemporânea cinzento claro para projetos residenciais e comerciais.',
      descricaoLonga: 'Revestimento com estética contemporânea em tons cinzento claro. Ideal para projetos modernos e minimalistas.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Liso',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Escritório, Fachada',
      imagens: ['cimenticio-alpino-frontal.webp', 'cimenticio-alpino-frontal-1.webp', 'cimenticio-alpino-frontal-2.webp', 'cimenticio-alpino-frontal-3.webp'],
      arquivo: 'produto-cimenticio-alpino.html'
    },
    {
      id: 'grigio',
      nome: 'Grigio',
      categoria: 'Cimentício',
      sku: 'Cimentício',
      preco: '169,90',
      descricao: 'Estética contemporânea cinzento para projetos residenciais e comerciais.',
      descricaoLonga: 'Revestimento com estética contemporânea em tons cinzento. Oferece acabamento industrial sofisticado.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Liso',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Escritório, Fachada',
      imagens: ['cimenticio-grigio-frontal.webp', 'cimenticio-grigio-frontal-1.webp', 'cimenticio-grigio-frontal-2.webp', 'cimenticio-grigio-frontal-3.webp'],
      arquivo: 'produto-cimenticio-grigio.html'
    },
    {
      id: 'urban',
      nome: 'Urban',
      categoria: 'Cimentício',
      sku: 'Cimentício',
      preco: '169,90',
      descricao: 'Estética urbana e contemporânea com acabamento robusto.',
      descricaoLonga: 'Revestimento com estética urbana e contemporânea que oferece acabamento robusto para fachadas modernas.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Liso',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Sala de estar, Escritório, Fachada',
      imagens: ['cimenticio-urban-frontal.webp', 'cimenticio-urban-frontal-1.webp', 'cimenticio-urban-frontal-2.webp', 'cimenticio-urban-frontal-3.webp'],
      arquivo: 'produto-cimenticio-urban.html'
    }
  ],
  rockface: [
    {
      id: 'brisa',
      nome: 'Brisa',
      categoria: 'Rockface',
      sku: 'Rockface',
      preco: '169,90',
      descricao: 'Acabamento contemporâneo com textura de pedra natural.',
      descricaoLonga: 'Revestimento com acabamento contemporâneo e textura de pedra natural. Perfeito para fachadas sofisticadas.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Texturado',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Fachada, Parede externa, Destaque',
      imagens: ['rockface-brisa-frontal.webp', 'rockface-brisa-frontal-1.webp', 'rockface-brisa-frontal-2.webp', 'rockface-brisa-frontal-3.webp'],
      arquivo: 'produto-rockface-brisa.html'
    },
    {
      id: 'alpino-rockface',
      nome: 'Alpino',
      categoria: 'Rockface',
      sku: 'Rockface',
      preco: '229,90',
      descricao: 'Ótimo custo-benefício, instalação prática e aparência natural.',
      descricaoLonga: 'Revestimento rockface com ótimo custo-benefício e instalação prática. Oferece aparência natural e durável.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Texturado',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Fachada, Parede externa, Destaque',
      imagens: ['rockface-alpino-frontal.webp', 'rockface-alpino-frontal-1.webp', 'rockface-alpino-frontal-2.webp', 'rockface-alpino-frontal-3.webp'],
      arquivo: 'produto-rockface-alpino.html'
    },
    {
      id: 'grigio-rockface',
      nome: 'Grigio',
      categoria: 'Rockface',
      sku: 'Rockface',
      preco: '229,90',
      descricao: 'Ótimo custo-benefício, instalação prática e aparência natural.',
      descricaoLonga: 'Revestimento rockface cinzento com ótimo custo-benefício. Oferece profundidade visual natural.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Texturado',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Fachada, Parede externa, Destaque',
      imagens: ['rockface-grigio-frontal.webp', 'rockface-grigio-frontal-1.webp', 'rockface-grigio-frontal-2.webp', 'rockface-grigio-frontal-3.webp'],
      arquivo: 'produto-rockface-grigio.html'
    },
    {
      id: 'urban-rockface',
      nome: 'Urban',
      categoria: 'Rockface',
      sku: 'Rockface',
      preco: '229,90',
      descricao: 'Ótimo custo-benefício, instalação prática e aparência natural.',
      descricaoLonga: 'Revestimento rockface urbano com ótimo custo-benefício. Oferece resultado diferenciado e sofisticado.',
      dimensoes: '240mm x 65mm x 12mm',
      acabamento: 'Texturado',
      resistencia: 'Classe A',
      aplicacao: 'Interno e externo',
      ambientes: 'Fachada, Parede externa, Destaque',
      imagens: ['rockface-urban-frontal.webp', 'rockface-urban-frontal-1.webp', 'rockface-urban-frontal-2.webp', 'rockface-urban-frontal-3.webp'],
      arquivo: 'produto-rockface-urban.html'
    }
  ]
};

// Função pra pegar todos os produtos em ordem
function getAllProducts() {
  return [...produtosData.brick, ...produtosData.cimenticio, ...produtosData.rockface];
}

// Função pra pegar produto por ID
function getProductById(id) {
  const allProducts = getAllProducts();
  return allProducts.find(p => p.id === id);
}
